---
ID: "7bed6b6c-4946-4808-90b3-87dcdcf16fba"
Parent: "8de8f843-019a-429b-a589-97a41f8d1c87"
Template: "8de8f843-019a-429b-a589-97a41f8d1c87"
Path: /sitecore/templates/Project/TRN/Website/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{35D4CDAF-5292-400B-80ED-7391A0E8F7D3}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240503T025348Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
